[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CopernicusClimateDataStore = "bce3f73f-acea-4481-bd86-df89ecc2cb46"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"

[compat]
CairoMakie = "0.12, 0.13"
NCDatasets = "0.14, 0.15"

